# Generated by Django 4.2.5 on 2023-09-29 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='open_close',
            name='schedule_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open_close', to='about.scheduletime'),
        ),
    ]
