# Generated by Django 4.2.5 on 2023-09-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_scheduletime_open_close_schedule_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='open_close',
            name='schedule_time',
        ),
        migrations.AddField(
            model_name='open_close',
            name='schedule_time',
            field=models.ManyToManyField(related_name='open_close', to='about.scheduletime'),
        ),
    ]
