# Generated by Django 4.2.5 on 2023-09-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_open_close_schedule_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='rest_add',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
    ]
