# Generated by Django 4.2.5 on 2023-09-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_address_rest_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(max_length=500)),
                ('explanation', models.TextField()),
                ('items', models.ManyToManyField(related_name='about', to='about.itemabout')),
            ],
        ),
    ]
