# Generated by Django 4.2.5 on 2023-09-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_itemabout_aboutmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='img',
            field=models.ImageField(null=True, upload_to='about/'),
        ),
    ]
