# Generated by Django 4.2.5 on 2023-10-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_aboutmodel_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='open_close',
            name='close',
        ),
        migrations.RemoveField(
            model_name='open_close',
            name='open',
        ),
    ]
