# Generated by Django 4.2.5 on 2023-10-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_remove_open_close_close_remove_open_close_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='open_close',
            name='close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='open_close',
            name='open',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
