# Generated by Django 4.2.5 on 2023-10-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_alter_open_close_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='facebook',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='instagram',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='linkedin',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='twitter',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
    ]
