# Generated by Django 4.2.5 on 2023-10-07 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_address_facebook_address_instagram_address_linkedin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='facebook',
            new_name='telegram',
        ),
        migrations.RemoveField(
            model_name='address',
            name='twitter',
        ),
    ]
